language: python
python:
  - "3.4"
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements/base.txt
  - pip install -r requirements/dev.txt
# command to run tests
script:
  - pytest --cov=./


after_success:
  - codecov
